# exporter_schem.py
import os
import numpy as np
import nbtlib
from nbtlib import Compound, List
from nbtlib.tag import Int, Short, String, ByteArray

def write_schem(block_ids_3d, path):
    """
    block_ids_3d: np.ndarray (W,H,D) containing either None or 'minecraft:block' strings.
    Writes Sponge .schem v2 with:
      - minecraft:air at palette id 0
      - BlockData as 16-bit indices (little-endian) in Y-major order
      - Optional tags WorldEdit/FAWE like to see (BlockEntities, Entities, Metadata offsets)
    Returns (abs_path, file_size_bytes)
    """
    # Resolve output path and ensure dir exists
    path = os.path.abspath(os.path.expanduser(path))
    os.makedirs(os.path.dirname(path), exist_ok=True)

    W, H, D = block_ids_3d.shape

    # ---- Palette: air first ----
    unique_blocks = sorted({b for b in block_ids_3d.flatten() if b is not None})
    palette = {"minecraft:air": 0}
    next_id = 1
    for b in unique_blocks:
        if b not in palette:
            palette[b] = next_id
            next_id += 1

    # ---- Y-major order index: idx = y*(W*D) + z*W + x ----
    def idx(x, y, z):
        return y * (W * D) + z * W + x

    # ---- Fixed-width int16 indices (default = air=0), LITTLE ENDIAN ----
    arr = np.zeros(W * H * D, dtype="<i2")  # <i2 = little-endian int16
    for x in range(W):
        for y in range(H):
            for z in range(D):
                b = block_ids_3d[x, y, z]
                if b is not None:
                    arr[idx(x, y, z)] = palette[b]

    # Pack to bytes
    block_bytes = arr.view(np.uint8)  # raw bytes in little-endian order

    # ---- Optional lists WE expects (even empty) ----
    block_entities = List[Compound]([])  # no block entities
    entities = List[Compound]([])        # no entities

    # ---- Metadata (offsets help with //paste -o) ----
    metadata = Compound({
        "WEOffsetX": Int(0),
        "WEOffsetY": Int(0),
        "WEOffsetZ": Int(0),
        # Optional: store author/desc for debugging
        "Author": String("scan2schem"),
        "Description": String("Generated by CPU pipeline"),
    })

    # ---- Build NBT ----
    file = nbtlib.File({
        "Schematic": Compound({
            "Version": Int(2),            # Sponge v2
            "DataVersion": Int(3120),     # 1.20.x works; not critical
            "Width":  Short(W),
            "Height": Short(H),
            "Length": Short(D),
            "PaletteMax": Int(len(palette)),                       # ok to include
            "Palette": Compound({k: Int(v) for k, v in palette.items()}),
            "BlockData": ByteArray(block_bytes.tolist()),          # explicit ByteArray list
            "BlockEntities": block_entities,
            "Entities": entities,
            "Metadata": metadata,
        })
    })

    file.save(path)
    size = os.path.getsize(path)
    return path, size

